### PR TITLE
feat: add Tap Tempo button and fix NeptunePackager-ProjectExtractor compatibility

### LINKED ISSUE #201: Link the NeptunePackager to the ProjectExtractor
After importing a file from phone storage, the ZIP created by NeptunePackager cannot be acces by ProjectExtractor, which cause that the audio isn't imported in samplerScreen. The task is about to fix this problem, by refactoring NeptunePager to be compatible with ProjectExtractor.

### PR DESCRIPTION
**Pull request by Ryukriss-f**
# What Changes
This pull request adds a Tap Tempo button to the TempoRow and fixes the issue where ZIP files created by NeptunePackager were inaccessible by ProjectExtractor.

## Key Implementations :
- Create a clickable `TapTempo` button that calculate the average number of touch user does over time and determine tempo beat  per minute from it.
- Refactor `NeptunePackager` and `SamplerViewModel` to ensure compatibility with `ProjectExtractor` when importing files from phone storage.
## Notes
Closes #201 #240

### CODE REVIEW

File: app/src/androidTest/java/com/neptune/neptune/screen/InitialSetupDialogTest.kt [hunk 1]
```diff
@@ -135,4 +137,15 @@ class InitialSetupDialogTest {
       assertEquals(false, state.showInitialSetupDialog)
     }
   }
+
+  @Test
+  fun tapTempoButton_updatesTempo() {
```
Comment (uri-j) [inline app/src/androidTest/java/com/neptune/neptune/screen/InitialSetupDialogTest.kt]: Functions should follow the camel case naming convention 👍👍👍👍

File: app/src/main/java/com/neptune/neptune/ui/sampler/SamplerScreen.kt [hunk 2]
```diff
@@ -1460,36 +1464,35 @@ fun TimeDisplay(playbackPosition: Float, audioDurationMillis: Int, modifier: Mod
...
+                  onTempoChange = viewModel::updateInputTempo,
+                  onTapTempo = viewModel::tapTempo)
 
               PitchSelectorField(
                   pitchNote = uiState.inputPitchNote,
                   pitchOctave = uiState.inputPitchOctave,
-                  onPitchUp = { viewModel.increaseInputPitch() },
-                  onPitchDown = { viewModel.decreaseInputPitch() },
+                  onPitchUp = viewModel::increaseInputPitch,
+                  onPitchDown = viewModel::decreaseInputPitch,
```
Comment (uri-j) [inline app/src/main/java/com/neptune/neptune/ui/sampler/SamplerScreen.kt]: Pretty lambda 😳😳😳😳😳

File: app/src/main/java/com/neptune/neptune/ui/sampler/SamplerScreen.kt [hunk 3]
```diff
@@ -1502,6 +1505,58 @@ fun InitialSetupDialog(viewModel: SamplerViewModel) {
...
 
+@Composable
+fun PreviewAudioRow(isPlaying: Boolean, onPlay: () -> Unit, onStop: () -> Unit) {
+  Row(
+      modifier = Modifier.fillMaxWidth(),
+      verticalAlignment = Alignment.CenterVertically,
+      horizontalArrangement = Arrangement.spacedBy(12.dp)) {
+        Button(
+            onClick = { if (isPlaying) onStop() else onPlay() },
+            modifier = Modifier.testTag("PREVIEW_PLAY_BUTTON")) {
```
Comment (uri-j) [inline app/src/main/java/com/neptune/neptune/ui/sampler/SamplerScreen.kt]: Test tag should be a value from the SamplerScreen test tags 😨😨😨😨😨😨

File: app/src/main/java/com/neptune/neptune/ui/sampler/SamplerViewModel.kt [hunk 4]
```diff
@@ -255,6 +258,50 @@ open class SamplerViewModel() : ViewModel() {
...
   }
 
+  private var previewPlayer: MediaPlayer? = null
+
+  private val tapTimes = mutableListOf<Long>()
+
+  fun playPreview(context: Context) {
+    stopPreview()
+
+    val uri = uiState.value.currentAudioUri ?: return
```
Comment (uri-j) [inline app/src/main/java/com/neptune/neptune/ui/sampler/SamplerViewModel.kt]: Value name isn't precise

File: app/src/main/java/com/neptune/neptune/ui/sampler/SamplerViewModel.kt [hunk 5]
```diff
@@ -484,19 +531,59 @@ open class SamplerViewModel() : ViewModel() {
...
+          _uiState.update {
+            it.copy(
+                showInitialSetupDialog = false,
+                currentAudioUri = null,
+                projectLoadError = "ZIP not found")
+          }
+          return@launch
+        }
+
+        val metadata: SamplerProjectMetadata =
```
Comment (uri-j) [inline app/src/main/java/com/neptune/neptune/ui/sampler/SamplerViewModel.kt]: I think it shouldn't be named "metadata" because it is indeed data from inside the project

File: app/src/test/java/com/neptune/neptune/data/NeptunePackagerTest.kt [hunk 6]
```diff
@@ -25,10 +25,10 @@ class NeptunePackagerTest {
 
   @Test
   fun createProjectZipCreatesUniqueZipInsideWorkspace() =
-      runTest(testDispatcher) {
+      runTest(testDispatcher) { // La coroutine est déjà lancée ici
```
Comment (uri-j) [inline app/src/test/java/com/neptune/neptune/data/NeptunePackagerTest.kt]: Comments shouldn't be in french

**Review by uri-j — CHANGES_REQUESTED** [review]
Nice PR overall, the Sampler files are a bit hard to work with, because of previous PR which were a bit unclean, WE CAN FINALLY  🤗🤗🤗🤗

Not sure if it is related to your PR, but when testing with an imported audio file ("Yo le rap, yo le rap"), the waveform seems not to appear as expected 😔😔😔😔
